### ISSUE TITLE
Flycheck not getting the flags cmake-ide sets

### ISSUE THREAD

**Issue by BlueFlo0d** [atilaneves/cmake-ide#189]
The cmake-ide sets flags for clang properly and company works well. However, I installed flycheck and seems that it didn't get the flags properly.
What I have in my init.el is simply:
<code>
(global-flycheck-mode 1)
(cmake-ide-setup)
</code>
and whenever I run flycheck-list-errors I get something like <stdio.h> not found.

**Comment by atilaneves** [comment]
From the readme:

"If `cmake-ide-flags-c` or `cmake-ide-flags-c++` are set, they will be
added to `ac-clang-flags` and `company-clang-arguments`.  These
variables should be set. Particularly, they should contain the system
include paths (e.g. `'("-I/usr/include/c++/4.9.1" "...")`. For a
system with gcc, you can get this information by running `gcc -v -xc++
/dev/null -fsyntax-only` (it's the same prerequisite for
`auto-complete-clang` to work, since that's how clang itself works)."
