### ISSUE TITLE
Set flycheck-clang-language-standard

### ISSUE THREAD

**Issue by pmiddend** [atilaneves/cmake-ide#30]
I have a project that uses -std=c++14. flycheck (with cmake-ide) marks all C++14 additions as errors. When I manually set the variable flycheck-clang-language-standard to the string "c++14", it works. Since being as 0-config as possible as one of the goals of cmake-ide, maybe we can get rid of this manual setup step, too?

**Comment by yhagerjs** [comment]
I have the same issue.

**Comment by atilaneves** [comment]
I write C++14 when I write C++. Either this was before `flycheck-clang-language-standard` or I just didn't know about it. The way I went about it is to integrate `cmake-ide-flags-c++` with the flags from the project and I've set `cmake-ide-flags-c++` to have `-std=c++14` ever since, so that's a workaround.

I'll see what I can do, but I need an example project where not setting `flycheck-clang-language-standard` fails first.
