### ISSUE TITLE
flycheck-clang-args: unable to specify -Isystem in .dir-locals.el

### ISSUE THREAD

**Issue by Fillipoman** [atilaneves/cmake-ide#46]
I am trying to set the -Isystem flag of flycheck-clang-args in my .dir-locals.el as so:

((c++-mode . ((flycheck-clang-args . ("-isystem/path/to/3rd-party-libs/include")))))

When cmake-ide is running, flycheck-clang-args is overwritten so this has no effect. I also tried setting -Isystem with the cmake-ide-flags-c++ variable instead. However, from reading the cmake-ide.el file it appears that the -I flags are filtered out?

I want to be able to do this so that flycheck-clang will ignore the errors for the third party libraries that I specify. Otherwise, I see errors at the #include lines for the third party library headers. Alternative solutions are welcome.

Thanks.

**Comment by ennokde** [comment]
Shouldn't this information be stated in or found by the CMakeLists.txt file of your project?
For example <code>find_package(3rd-party-library)</code> or <code>include_directories(something somewhere)</code>?
Otherwise I would expect your compiler to have the same issues finding the includes when you try to build the project.

**Comment by atilaneves** [comment]
There was a bug that filtered out by mistake `-i` flags. Can you check that `cmake-ide-flags-c++` still doesn't work with the latest version? Thanks.

**Comment by Fillipoman** [comment]
@ennokde Yeah, cmake-ide is finding the path to the library from my include_directories call so it doesn't have a problem finding the header. The issue is thatin any file I do #include <singleHeaderLibrary.h> in any file flycheck-clang puts a squiggly red line under the include with the messages: error "In include path/to/singleHeaderLibrary.h" and error "In file included from".

@atilaneves After updating, it looks like the -isystem flag is still filtered out from the flags when flycheck-clang-args is set in cmake-ide.el. However, I did further investigation and was able to set the -isystem flag to flycheck-clang-args which did not fix my issue of the errors being surfaced at the #include <singleHeaderLibrary.h> lines. This thread https://github.com/flycheck/flycheck/pull/521 lead me to believe it would resolve the issue, however setting the path on -isystem appears to only suppress warnings from the file and not errors.

I will need to either live with the errors (although they seem to kill further processing of the file with flycheck), find an alternative library to use, or disable flycheck-clang.

Thanks for your time and sorry for the bother.

**Comment by duerrp** [comment]
I had the same issue as @Fillipoman, and after investigating the sources it turns out cmake-ide does not add the `cmake-ide-flags-c++` to the `flycheck-clang-args` at all. In my emacs config, I fixed this with

```
(defun fix-clang-args (orig-fun &rest args)
 (let ((clang-args flycheck-clang-args))
  (apply orig-fun args)
  (setq flycheck-clang-args (append flycheck-clang-args clang-args))))(advice-add 'cmake-ide--set-flags-for-file :around #'fix-clang-args)
``` 
Not sure if this breaks something for different setups though... maybe worth investigating.

(Btw., thanks for cmake-ide, it's a great package!)
