### ISSUE TITLE
2 general questions

### ISSUE THREAD

**Issue by astoeckley** [atilaneves/cmake-ide#58]
Hello!

In my quest to research how effective emacs can be as a c++ ide, I have come across this repo. I am working in an environment where clang is not available, so my first question is whether there is any problem or limitation with using GCC/G++ instead of clang?

My next question is about the architecture of cmake-ide: how does this setup compare or overlap with the functionality outlined in these many videos about using emacs for c++:

https://www.youtube.com/watch?v=HTUE03LnaXA

The packages used in those videos are: http://barisyuksel.com/cppmode/package_versions.png

There are so many packages out there and I'm not an emacs expert, but I do know that many different packages tend to compete with each other for functionality. Does the cmake-ide solution bundle together the functionality mentioned in these other packages/videos?

Many thanks!

**Comment by atilaneves** [comment]
You can compile with gcc, but some packages rely on clang and there's nothing I can do about that (flycheck, auto-complete-clang) Try and see, I guess.

As for other options, I only wrote my own because I thought the others were worse. If you ask my opinion, I'm obviously going to tell you to use cmake-ide ;) The only way you can make a decision is to try them all, I'm afraid.
