### ISSUE TITLE
System include for company-c-headers not working

### ISSUE THREAD

**Issue by Franzo-** [atilaneves/cmake-ide#78]
Autocompletion of C and C++ system headers always return no result. Instead, project local headers are completed as expected.

I did a bit of debugging and I found out that the `company-c-headers-path-system` variable is set to nil by the function `cmake-ide-set-compiler-flags`. The input parameter `sys-includes` of this function is nil and the reason seems to be that the system include flags could not be found in the project's compile_commands.json file.

An example of compile_commands.json generated by CMake on my system:
```json
{
  "directory": "/home/franzo/Workspaces/cmake_test/build",
  "command": "/usr/local/bin/c++    -I/home/franzo/Workspaces/cmake_test/include    -o CMakeFiles/cmake_test.dir/src/cmake_test.cpp.o -c /home/franzo/Workspaces/cmake_test/src/cmake_test.cpp",
  "file": "/home/franzo/Workspaces/cmake_test/src/cmake_test.cpp"
}
```

CMake seems to avoid writing the system include flags, but the project local include directory is present. Am I missing any cmake-ide or CMake configuration to also enable system include flags in compile_commands.json?

My system informations:
```
$ uname -a
Linux Xubuntu-16-10 4.8.0-27-generic #29-Ubuntu SMP Thu Oct 20 21:03:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cmake --version
cmake version 3.5.2
$ emacs --version
GNU Emacs 26.0.50.2
```

Thanks.

**Comment by atilaneves** [comment]
From the README:

If cmake-ide-flags-c or cmake-ide-flags-c++ are set, they will be added to ac-clang-flags and company-clang-arguments. These variables should be set. Particularly, they should contain the system include paths (e.g. '("-I/usr/include/c++/4.9.1" "..."). For a system with gcc, you can get this information by running gcc -v -xc++ /dev/null -fsyntax-only (it's the same prerequisite for auto-complete-clang to work, since that's how clang itself works).

I'm not sure I tried it manually with company though.

**Comment by Franzo-** [comment]
Yes, I manually set `cmake-ide-flags-c` and `cmake-ide-flags-c++` in init.el and their values are mantained when I open a source file of my C++ project. On the other hand, I also set a global value for `company-c-headers-path-system` (used by company-c-headers for autocompletion) in init.el, but, in the source file buffer, this value is overwritten by a local one which is nil. So, autocompletion works everywhere except when I try to autocomplete an header.

The culprit seems to be the parameter `sys-includes` of the `cmake-ide-set-compiler-flags` function, which its called by cmake-ide every time I open a new source file of my C++ project. But `sys-includes` is nil because there are no system include flags in compile_commands.json.

I also see that `sys-includes` is used in that function to set some flycheck related variables, so, if its value is nil, it could cause problems even to flycheck. But I personally have not seen any problem with flycheck so far...

**Comment by atilaneves** [comment]
I never even had the relevant package installed, so I'd never tried this myself. git tells me I wasn't the one who wrote those lines. I installed `company-c-headers` and, as you say, it gets set to `nil` locally. I think this was a misunderstanding of what `sys-includes` means - it's not the system include paths at all. And it's wrong to reset instead of adding to it. So I'll fix this.
