### ISSUE TITLE
cmake-ide--idb-file-to-obj: Wrong type argument, hash-table-p, nil

### ISSUE THREAD

**Issue by Red-Portal** [atilaneves/cmake-ide#93]
![image](https://cloud.githubusercontent.com/assets/18320033/23738250/27001758-04db-11e7-99be-60f53e209acf.png)

stumbled upon this problem.
what are the reasons for this problem?

**Comment by dlyr** [comment]
Hi, it seems that the compile_commands.json was not generated. It happens to me when cmake failed (look in the *cmake* buffer if anything went right, or run cmake in terminal in a separate build dir)
By the way, could you simple copy paste text rather than a screen shot ? I think it's a best practice.
++ dlyr

**Comment by martinxyz** [comment]
For people finding this via google: more likely the actual problem was an existing in-source build. See my fix in #185). If it was a cmake failure, there should have been a message after "finished running cmake".
