### ISSUE TITLE
passing flags to make when using cmake-ide-compile (-j4)

### ISSUE THREAD

**Issue by yavitzour** [atilaneves/cmake-ide#97]
Hi,

Is there a good way to pass a flag to make, e.g. -j4 (compile with 4 cores)?
Currently I changed the line in cmake-ide--get-compile-command from:

(concat cmake-ide-make-command " -C " dir)

to:

(concat cmake-ide-make-command " -j4 -C " dir)

but I was wondering if there were a better way to do it.

Thanks

**Comment by atilaneves** [comment]
Add the `-j4` to `cmake-ide-flags-c` and/or `cmake-ide-flags-c++`. Or in this specific case of `-j4`, just use ninja, which is way better than make anyway ;)

**Comment by myrgy** [comment]
@yavitzour , try to use helm-make. This package is nice addition to cmake-ide.
It allows to switch compilation target and specify make -j4 options.

**Comment by Deanseo** [comment]
> Add the -j4 to cmake-ide-flags-c and/or cmake-ide-flags-c++.
Does this solution still work at the newest version? 

```
(use-package cmake-ide
  :ensure t
  ;;; ...
  :config
  (setq cmake-ide-flags-c++ "-j4"))
```

**Comment by atilaneves** [comment]
`-j4` isn't a C++ compiler command-line parameter, it's a `make` or `ninja` one. You _can_ set `cmake-ide-compile-command` to `make -j4` however.

**Comment by Deanseo** [comment]
I see, so [what you suggested](https://github.com/atilaneves/cmake-ide/issues/97#issuecomment-289694534) above is no longer a valid approach, and we can use `cmake-ide-compile-command` instead.

That's good, but that overwrites the whole `make` command, instead of adding the given parameter to `make`, which is not ideal because then `cmake-ide-compile` won't be able to build for the missing build path.

For example,
If I call `cmake-ide-compile`, the **default** `make` command goes:

```
make --no-print-directory -C <your build path>
```

After manipualting `cmake-ide-compile-command`, it goes:

```
;; (setq cmake-ide-compile-command "make -j4")
make -j4
make: *** No targets specified and no makefile found.  Stop.
```

Can we selectively add some `make` parameters` without having to make direct changes to `cmake-ide.el`? If not, open to a PR?

**Comment by dlyr** [comment]
I use `(setq cmake-ide-make-command "make -j8")` which works fine for me. (well I'm not up to date with last version).

**Comment by atilaneves** [comment]
> I see, so what you suggested above is then no longer a valid approach?

I don't think that was ever a valid approach, I don't know what I was thinking when I wrote that.

> That's fine, but that overwrites the whole make command, instead of adding the given parameter to make, 

You could overwrite the whole make command yourself as well.

> If we can't at the current stage, open to a PR?

I'm open, yes, but I don't know how that would work. I'd suggest just using `ninja` and forgetting about manually specifying how many threads to use.
